version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # Install Snyk globally
      - npm install -g snyk
  pre_build:
    commands:
      # Authenticate Snyk using your API token
      - snyk auth 9bc62721-b0d1-4ba3-9d7d-71f85c0f712f
  build:
    commands:
      # Run Snyk test to check for vulnerabilities
      - snyk test --all-projects --json > snyk_output.json

artifacts:
  files: snyk_output.json

post_build:
  commands:
    # Monitor vulnerabilities and fail the build if found
    - snyk monitor --all-projects --json > snyk_monitor_output.json
    - if [ "$(cat snyk_output.json | jq -r '.vulnerabilities.length')" -gt 0 ]; then echo "Vulnerabilities found. Failing the build."; exit 1; fi
